- name: restart apache
  service:
    name: apache
    state: restarted

- name: start apache
  service:
    name: apache
    state: started

- name: reload apache
  service:
    name: apache
    state: reloaded